<?php 
add_action( 'vc_before_init', 'vc_add_customopton' );
function vc_add_customopton() {
$attributes = array( 
	array(
		"type" => "dropdown",
		'group' => 'Row Height',
		"heading" => "Row Height",
		"param_name" => "section_heights",
		"value" => array(
			"Select" => "auto", 
			"10vh" => "10vh", 
			"20vh " => "20vh", 
			"30vh " => "30vh", 
			"40vh " => "40vh", 
			"50vh " => "50vh", 
			"60vh " => "60vh", 
			"70vh " => "70vh", 
			"80vh " => "80vh", 
			"90vh " => "90vh", 
			"100vh " => "100vh", 
			"110vh " => "110vh", 
			"120vh " => "120vh", 
			"130vh " => "130vh", 
			"140vh " => "140vh", 
			"150vh " => "150vh", 
		) ,
	),
	array(
        'type' => 'colorpicker',
        'heading' => esc_html__('Background Overlay Color', 'risehand-addons') ,
        'param_name' => 'overlay_color',
        'value' => '',
		'group' => 'Row Height',
    ),
	array(
		"type" => "dropdown",
		'group' => 'Row Height',
		"heading" => "Overlay Z Index",
		"param_name" => "overlay_z_index_select",
		"value" => array(
			"0"  => "0",
			"1" => "1",
			"2" => "2",
			"3" => "3",
			"4" => "4",
			"5" => "5",
			"6" => "6",
			"7" => "7",
			"8" => "8",
			"9" => "9",
			"99" => "99",
			"999" => "999",
			"9999" => "9999" 
		) ,
	),
	array(
		"type" => "dropdown",
		'group' => esc_html__('Risehand Layout Options', 'risehand-addons') ,
		"heading" => "Contnet Spacing",
		"param_name" => "layout",
		"value" => array(
			"Auto Container" => "auto-container", 
			"Container " => "container",
			'Small container'  => "small-container",
			"Medium Container" => "medium-container", 
			"Large Container" => "large-container",
			"Extra Largre Container " => "full-container",
			"Full Container" => "container-fluid",
		) ,
		'std' => 'auto-container'
	),
	array(
		"type" => "dropdown",
		'group' => esc_html__('Design Options', 'risehand-addons') ,
		"heading" => "Background Position",
		"param_name" => "bg_positions",
		"value" => array(
			"Select Background Position" => "", 
			"Left" => "left", 
			"Right " => "right",
			'Center'  => "center",
			"Top" => "top", 
			"Top Left" => "top left", 
			"Top Right" => "top right", 
			"Bottom" => "bottom",
			"Bottom Left" => "bottom left",
			"Bottom Right" => "bottom right",
			"Cutom Position" => "custom", 
		) ,
	),
	array(
		'type' => 'textfield',
		'heading' => esc_html__('Background Position Text', 'risehand-addons') ,
		'param_name' => 'bg_position_text', 
		'description' => esc_html__('Enter background position eg( https://developer.mozilla.org/en-US/docs/Web/CSS/background-position )', 'risehand-addons') ,
		'group' => esc_html__('Design Options', 'risehand-addons') ,
		'dependency' => array(
			'element' => 'bg_positions',
			'value' => 'custom',
		),
	),
	array(
		'type' => 'textfield',
		'heading' => esc_html__('Enter Background Position for Laptop', 'risehand-addons') ,
		'param_name' => 'bg_position_text_lap', 
		'description' => esc_html__('Enter background position for Laptop eg( https://developer.mozilla.org/en-US/docs/Web/CSS/background-position )', 'risehand-addons') ,
		'group' => esc_html__('Design Options', 'risehand-addons') , 
	),
	array(
		'type' => 'textfield',
		'heading' => esc_html__('Enter Background Position Text for Tablet', 'risehand-addons') ,
		'param_name' => 'bg_position_text_tab', 
		'description' => esc_html__('Enter background position for Tablet eg( https://developer.mozilla.org/en-US/docs/Web/CSS/background-position )', 'risehand-addons') ,
		'group' => esc_html__('Design Options', 'risehand-addons') , 
	),
	array(
		'type' => 'textfield',
		'heading' => esc_html__('Enter Background Position Text for Mobile', 'risehand-addons') ,
		'param_name' => 'bg_position_text_mob', 
		'description' => esc_html__('Enter background position for Mobile eg( https://developer.mozilla.org/en-US/docs/Web/CSS/background-position )', 'risehand-addons') ,
		'group' => esc_html__('Design Options', 'risehand-addons') , 
	),
	array(
		'type' => 'textfield',
		'heading' => esc_html__('Layout Padding', 'risehand-addons') ,
		'param_name' => 'layout_padding', 
		'description' => esc_html__('Add Your Padding like this - top , right , bottom , left (0px 0px 0px 0px) px , rem ,em', 'risehand-addons') ,
		'group' => esc_html__('Risehand Layout Options', 'risehand-addons') ,
	),
	array(
		'type' => 'textfield',
		'heading' => esc_html__('Layout Laptop Padding', 'risehand-addons') ,
		'param_name' => 'layout_lap_padding',
		'description' => esc_html__('Add Your Laptop Padding like this - top , right , bottom , left (0px 0px 0px 0px) px , rem ,em', 'risehand-addons') ,
		'group' => esc_html__('Risehand Layout Options', 'risehand-addons') ,
	), 
	array(
		'type' => 'textfield',
		'heading' => esc_html__('Layout Tablet Padding', 'risehand-addons') ,
		'param_name' => 'layout_tab_padding',
		'description' => esc_html__('Add Your Tablet Padding like this - top , right , bottom , left (0px 0px 0px 0px) px , rem ,em', 'risehand-addons') ,
		'group' => esc_html__('Risehand Layout Options', 'risehand-addons') ,
	), 
	array(
		'type' => 'textfield',
		'heading' => esc_html__('Layout Mobile Padding', 'risehand-addons') ,
		'param_name' => 'layout_mobile_padding',
		'description' => esc_html__('Add Your Mobile Padding like this - top , right , bottom , left (0px 0px 0px 0px) px , rem ,em', 'risehand-addons') ,
		'group' => esc_html__('Risehand Layout Options', 'risehand-addons') ,
	), 
	array(
		'type' => 'textfield',
		'heading' => esc_html__('Layout Border Width', 'risehand-addons') ,
		'param_name' => 'layout_border_width',
		'description' => esc_html__('Add Your Border Width like this - (0px) px , rem ,em', 'risehand-addons') ,
		'group' => esc_html__('Risehand Layout Options', 'risehand-addons') ,
	),
	array(
		"type" => "dropdown",
		'group' => esc_html__('Risehand Layout Options', 'risehand-addons') ,
		"heading" => "Border Style",
		"param_name" => "layout_border_style",
		"value" => array(
			'Select Border Style'  => "",
			"Solid" => "solid",
			"Dotted" => "dotted",
			"Dashed" => "dashed",
			"None" => "none",
			"Hidden" => "hidden",
			"Double" => "double",
			"Groove" => "groove",
			"Ridge" => "ridge",
			"Inset" => "inset",
			"Outset" => "outset",
			"Initial" => "initial",
			"Inherit" => "inherit" 
		) ,
	),
	array(
        'type' => 'colorpicker',
        'heading' => esc_html__('Layout Border Color', 'risehand-addons') ,
        'param_name' => 'layout_border_color',
        'value' => '',
        'group' => esc_html__('Risehand Layout Options', 'risehand-addons') ,
    ), 
	array(
        'type' => 'colorpicker',
        'heading' => esc_html__('Layout Background Color', 'risehand-addons') ,
        'param_name' => 'layout_background_color',
        'value' => '',
        'group' => esc_html__('Risehand Layout Options', 'risehand-addons') ,
    ),
	array(
		'type' => 'textfield',
		'heading' => esc_html__('Layout Border Radius ', 'risehand-addons') ,
		'param_name' => 'layout_border_radius',
		'description' => esc_html__('Add border radius  like this - 10px 10px 10px 10px', 'risehand-addons') ,
		'value' => '' ,
		'group' => esc_html__('Risehand Layout Options', 'risehand-addons') ,
	),
	array(
		'type' => 'textfield',
		'heading' => esc_html__('Layout Boxshadow Numbers', 'risehand-addons') ,
		'param_name' => 'layout_box_shadow',
		'description' => esc_html__('Add Box shadow numbers like this - 0px 5px 22px 0px', 'risehand-addons') ,
		'value' => '0px 5px 22px 0px' ,
		'group' => esc_html__('Risehand Layout Options', 'risehand-addons') ,
	),
	array(
        'type' => 'colorpicker',
        'heading' => esc_html__('Layout Boxshadow Color', 'risehand-addons') ,
        'param_name' => 'layout_box_shadow_color',
        'value' => '',
        'group' => esc_html__('Risehand Layout Options', 'risehand-addons') ,
    ),
	array(
		"type" => "dropdown",
		'group' => esc_html__('Design Options', 'risehand-addons') ,
		"heading" => "Section Z Index",
		"param_name" => "z_index_select",
		"value" => array(
			"0"  => "0",
			"1" => "1",
			"2" => "2",
			"3" => "3",
			"4" => "4",
			"5" => "5",
			"6" => "6",
			"7" => "7",
			"8" => "8",
			"9" => "9",
			"99" => "99",
			"999" => "999",
			"9999" => "9999" 
		) ,
	),
	array(
		'type' => 'textfield',
		'heading' => esc_html__('Section Laptop Padding', 'risehand-addons') ,
		'param_name' => 'seclap_padding',
		'description' => esc_html__('Add Section Laptop Padding numbers like this - 0px 5px 22px 0px', 'risehand-addons') ,
		'value' => '' ,
		'group' => esc_html__('Design Options', 'risehand-addons') ,
	),
	array(
		'type' => 'textfield',
		'heading' => esc_html__('Section Tablet Padding', 'risehand-addons') ,
		'param_name' => 'sectab_padding',
		'description' => esc_html__('Add Section Tablet Padding numbers like this - 0px 5px 22px 0px', 'risehand-addons') ,
		'value' => '' ,
		'group' => esc_html__('Design Options', 'risehand-addons') ,
	),
	array(
		'type' => 'textfield',
		'heading' => esc_html__('Section Mobile Padding', 'risehand-addons') ,
		'param_name' => 'secmob_padding',
		'description' => esc_html__('Add Section Mobile Padding numbers like this - 0px 5px 22px 0px', 'risehand-addons') ,
		'value' => '' ,
		'group' => esc_html__('Design Options', 'risehand-addons') ,
	),
	array(
		'type' => 'textfield',
		'heading' => esc_html__('Section Laptop Margin', 'risehand-addons') ,
		'param_name' => 'seclap_margin',
		'description' => esc_html__('Add Section Laptop Margin numbers like this - 0px 5px 22px 0px', 'risehand-addons') ,
		'value' => '' ,
		'group' => esc_html__('Design Options', 'risehand-addons') ,
	),
	array(
		'type' => 'textfield',
		'heading' => esc_html__('Section Tablet Margin', 'risehand-addons') ,
		'param_name' => 'sectab_margin',
		'description' => esc_html__('Add Section Tablet Margin numbers like this - 0px 5px 22px 0px', 'risehand-addons') ,
		'value' => '' ,
		'group' => esc_html__('Design Options', 'risehand-addons') ,
	),
	array(
		'type' => 'textfield',
		'heading' => esc_html__('Section Mobile Margin', 'risehand-addons') ,
		'param_name' => 'secmob_margin',
		'description' => esc_html__('Add Section Mobile Margin numbers like this - 0px 5px 22px 0px', 'risehand-addons') ,
		'value' => '' ,
		'group' => esc_html__('Design Options', 'risehand-addons') ,
	),
	array(
		'type' => 'textfield',
		'heading' => esc_html__('Section Move Top', 'risehand-addons') ,
		'param_name' => 'secmov_top',
		'description' => esc_html__('Move Section top like this - (100px or -100px)', 'risehand-addons') ,
		'value' => '' ,
		'group' => esc_html__('Design Options', 'risehand-addons') ,
	),
	array(
		'type' => 'textfield',
		'heading' => esc_html__('Section Move Top On Laptop', 'risehand-addons') ,
		'param_name' => 'secmov_top_lap',
		'description' => esc_html__('Move Section top like on laptop this - (100px or -100px)', 'risehand-addons') ,
		'value' => '' ,
		'group' => esc_html__('Design Options', 'risehand-addons') ,
	),array(
		'type' => 'textfield',
		'heading' => esc_html__('Section Move Top on Tablet', 'risehand-addons') ,
		'param_name' => 'secmov_top_tab',
		'description' => esc_html__('Move Section top on tablet like this - (100px or -100px)', 'risehand-addons') ,
		'value' => '' ,
		'group' => esc_html__('Design Options', 'risehand-addons') ,
	),
	array(
		'type' => 'textfield',
		'heading' => esc_html__('Section Move Top Mobile', 'risehand-addons') ,
		'param_name' => 'secmov_top_mob',
		'description' => esc_html__('Move Section top like this - (100px or -100px)', 'risehand-addons') ,
		'value' => '' ,
		'group' => esc_html__('Design Options', 'risehand-addons') ,
	), 
	array(
		'type' => 'textfield',
		'heading' => esc_html__('Section Move Bottom', 'risehand-addons') ,
		'param_name' => 'secmov_bottom',
		'description' => esc_html__('Move Section bottom like this - (100px or -100px)', 'risehand-addons') ,
		'value' => '' ,
		'group' => esc_html__('Design Options', 'risehand-addons') ,
	),
	array(
		'type' => 'textfield',
		'heading' => esc_html__('Section Move Bottom on Laptop', 'risehand-addons') ,
		'param_name' => 'secmov_bottom_lap',
		'description' => esc_html__('Move Section bottom on laptop like this - (100px or -100px)', 'risehand-addons') ,
		'value' => '' ,
		'group' => esc_html__('Design Options', 'risehand-addons') ,
	),
	array(
		'type' => 'textfield',
		'heading' => esc_html__('Section Move Bottom on Tablet', 'risehand-addons') ,
		'param_name' => 'secmov_bottom_tab',
		'description' => esc_html__('Move Section bottom on tablet like this - (100px or -100px)', 'risehand-addons') ,
		'value' => '' ,
		'group' => esc_html__('Design Options', 'risehand-addons') ,
	),
	array(
		'type' => 'textfield',
		'heading' => esc_html__('Section Move Bottom Mobile', 'risehand-addons') ,
		'param_name' => 'secmov_bottom_mob',
		'description' => esc_html__('Move Section bottom on mobile like this - (100px or -100px)', 'risehand-addons') ,
		'value' => '' ,
		'group' => esc_html__('Design Options', 'risehand-addons') ,
	),

  );
  vc_add_params( 'vc_row', $attributes );
}
 
add_action( 'vc_before_init', 'vc_add_customopton_for_column' );
function vc_add_customopton_for_column() {
$attributes_column = array(  
	array(
		"type" => "dropdown",
		'group' => esc_html__('Design Options', 'risehand-addons') ,
		"heading" => "Background Position",
		"param_name" => "cbg_positions",
		"value" => array(
			"Select Background Position" => "", 
			"Left" => "left", 
			"Right " => "right",
			'Center'  => "center",
			"Top" => "top", 
			"Top Left" => "top left", 
			"Top Right" => "top right", 
			"Bottom" => "bottom",
			"Bottom Left" => "bottom left",
			"Bottom Right" => "bottom right",
			"Cutom Position" => "custom", 
		) ,
	),
	array(
		'type' => 'textfield',
		'heading' => esc_html__('Background Position Text', 'risehand-addons') ,
		'param_name' => 'cbg_position_text', 
		'description' => esc_html__('Enter background position', 'risehand-addons') ,
		'group' => esc_html__('Design Options', 'risehand-addons') ,
		'dependency' => array(
			'element' => 'cbg_positions',
			'value' => 'custom',
		),
	),
	array(
		'type' => 'textfield',
		'heading' => esc_html__('Enter Background Position for Laptop', 'risehand-addons') ,
		'param_name' => 'cbg_position_text_lap', 
		'description' => esc_html__('Enter background position for Laptop', 'risehand-addons') ,
		'group' => esc_html__('Design Options', 'risehand-addons') , 
	),
	array(
		'type' => 'textfield',
		'heading' => esc_html__('Enter Background Position Text for Tablet', 'risehand-addons') ,
		'param_name' => 'cbg_position_text_tab', 
		'description' => esc_html__('Enter background position for Tablet', 'risehand-addons') ,
		'group' => esc_html__('Design Options', 'risehand-addons') , 
	),
	array(
		'type' => 'textfield',
		'heading' => esc_html__('Enter Background Position Text for Mobile', 'risehand-addons') ,
		'param_name' => 'cbg_position_text_mob', 
		'description' => esc_html__('Enter background position for Mobile', 'risehand-addons') ,
		'group' => esc_html__('Design Options', 'risehand-addons') , 
	),
	array(
		'type' => 'textfield',
		'heading' => esc_html__('Column Padding for Laptop', 'risehand-addons') ,
		'param_name' => 'column_lap_padding', 
		'description' => esc_html__('Add Your Laptop Padding like this - top , right , bottom , left (0px 0px 0px 0px) px , rem ,em', 'risehand-addons') ,
		'group' => esc_html__('Design Options', 'risehand-addons') ,
	),
	array(
		'type' => 'textfield',
		'heading' => esc_html__('Column Padding for Tablet', 'risehand-addons') ,
		'param_name' => 'column_tab_padding', 
		'description' => esc_html__('Add Your Tablet Padding like this - top , right , bottom , left (0px 0px 0px 0px) px , rem ,em', 'risehand-addons') ,
		'group' => esc_html__('Design Options', 'risehand-addons') ,
	),
	array(
		'type' => 'textfield',
		'heading' => esc_html__('Column Padding for Mobile', 'risehand-addons') ,
		'param_name' => 'column_mobile_padding', 
		'description' => esc_html__('Add Your Mobile Padding like this - top , right , bottom , left (0px 0px 0px 0px) px , rem ,em', 'risehand-addons') ,
		'group' => esc_html__('Design Options', 'risehand-addons') ,
	),
	array(
		'type' => 'textfield',
		'heading' => esc_html__('Column Margin for Laptop', 'risehand-addons') ,
		'param_name' => 'column_lap_margin',
		'description' => esc_html__('Add Your Laptop Padding like this - top , right , bottom , left (0px 0px 0px 0px) px , rem ,em', 'risehand-addons') ,
		'group' => esc_html__('Design Options', 'risehand-addons') ,
	),
	array(
		'type' => 'textfield',
		'heading' => esc_html__('Column Margin for Tablet', 'risehand-addons') ,
		'param_name' => 'column_tab_margin',
		'description' => esc_html__('Add Your Laptop Padding like this - top , right , bottom , left (0px 0px 0px 0px) px , rem ,em', 'risehand-addons') ,
		'group' => esc_html__('Design Options', 'risehand-addons') ,
	),
	array(
		'type' => 'textfield',
		'heading' => esc_html__('Column Margin for Mobile', 'risehand-addons') ,
		'param_name' => 'column_mobile_margin',
		'description' => esc_html__('Add Your Mobile Padding like this - top , right , bottom , left (0px 0px 0px 0px) px , rem ,em', 'risehand-addons') ,
		'group' => esc_html__('Design Options', 'risehand-addons') ,
	),
	array(
		'type' => 'textfield',
		'heading' => esc_html__('Layout Border Radius ', 'risehand-addons') ,
		'param_name' => 'clayout_border_radius',
		'description' => esc_html__('Add border radius  like this - 10px 10px 10px 10px', 'risehand-addons') ,
		'value' => '' ,
		'group' => esc_html__('Design Options', 'risehand-addons') ,
	),
	array(
		'type' => 'textfield',
		'heading' => esc_html__('Layout Boxshadow Numbers', 'risehand-addons') ,
		'param_name' => 'clayout_box_shadow',
		'description' => esc_html__('Add Box shadow numbers like this - 0px 5px 22px 0px', 'risehand-addons') ,
		'value' => '0px 5px 22px 0px' ,
		'group' => esc_html__('Design Options', 'risehand-addons') ,
	),
	array(
        'type' => 'colorpicker',
        'heading' => esc_html__('Layout Boxshadow Color', 'risehand-addons') ,
        'param_name' => 'clayout_box_shadow_color',
        'value' => '',
		'group' => esc_html__('Design Options', 'risehand-addons') ,
    ),
	array(
		"type" => "dropdown",
		'group' => esc_html__('Design Options', 'risehand-addons') ,
		"heading" => "Column Z Index",
		"param_name" => "cz_index_select",
		"value" => array(
			"0"  => "0",
			"1" => "1",
			"2" => "2",
			"3" => "3",
			"4" => "4",
			"5" => "5",
			"6" => "6",
			"7" => "7",
			"8" => "8",
			"9" => "9",
			"99" => "99",
			"999" => "999",
			"9999" => "9999" 
		) ,
	),
  );
  vc_add_params( 'vc_column', $attributes_column );
}
  
 